// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for cancelling a workflow execution
 */
export type CancelWorkflowExecutionResponse = { workflow_execution_id: string, status: string, message: string, };
