// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for cancelling a workflow execution
 */
export type CancelWorkflowExecutionRequest = { 
/**
 * Optional reason for cancellation
 */
reason: string | null, };
