// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecuteWorkflowResponse = { workflow_execution_id: string, task_attempt_id: string, current_station_id: string | null, status: string, };
