// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutorProfileId } from "./ExecutorProfileId";

export type ExecuteWorkflowRequest = { task_id: string, base_branch: string, executor_profile_id: ExecutorProfileId | null, };
