// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for retrying a failed station
 */
export type RetryStationRequest = { station_execution_id: string, };
