// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for retrying a station
 */
export type RetryStationResponse = { workflow_execution_id: string, new_station_execution_id: string, status: string, message: string, };
