// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a station execution for the workflow execution response
 */
export type StationExecutionSummary = { id: string, station_id: string, station_name: string | null, status: string, output_data: string | null, started_at: string | null, completed_at: string | null, };
