// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationExecutionSummary } from "./StationExecutionSummary";

/**
 * Response for workflow execution with station details
 */
export type WorkflowExecutionDetailsResponse = { id: string, workflow_id: string, task_id: string, task_attempt_id: string | null, current_station_id: string | null, status: string, started_at: string | null, completed_at: string | null, created_at: string, updated_at: string, stations: Array<StationExecutionSummary>, };
