// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Auto-generated from Rust backend types using ts-rs

export type ApiResponse<T> = { success: boolean, data: T | null, message: string | null, };;

export type GitProvider = "Github" | "Gitlab" | "Bitbucket" | "Other";;

export type GitCredentialType = "Token" | "SshKey" | "OAuth";;

export type GitCredential = { id: string, user_id: string, provider: string, credential_type: GitCredentialType, created_at: Date, updated_at: Date, };;

export type CreateGitCredential = { provider: string, credential_type: GitCredentialType, credential: string, };;

export type CreateProject = { name: string, repo_url: string, repo_provider: GitProvider, git_credential_id: string | null, };;

export type Project = { id: string, name: string, owner_id: string, repo_url: string, repo_provider: GitProvider, git_credential_id: string | null, created_at: Date, updated_at: Date, };;

export type UpdateProject = { name: string | null, repo_url: string | null, repo_provider: GitProvider | null, git_credential_id: string | null | null, };;

export type CreateTask = { project_id: string, title: string, description: string | null, };;

export type Task = { id: string, project_id: string, title: string, description: string | null, status: TaskStatus, created_at: string, updated_at: string, };;

export type TaskStatus = "todo" | "inprogress" | "inreview" | "done" | "cancelled";;

export type UpdateTask = { title: string | null, description: string | null, status: TaskStatus | null, };;

export type CreateUser = { email: string, password: string, is_admin: boolean | null, };;

export type LoginRequest = { email: string, password: string, };;

export type LoginResponse = { user: User, token: string, };;

export type UpdateUser = { email: string | null, password: string | null, is_admin: boolean | null, };;

export type User = { id: string, email: string, is_admin: boolean, created_at: Date, updated_at: Date, };;
