#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}🔧 Setting up worktree development environment...${NC}"

# CRITICAL SAFETY CHECK: Prevent running in main repository
if [ -d .git ]; then
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${RED}❌ FATAL ERROR: This script MUST NOT run in the main repository!${NC}"
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e "${RED}This script is designed for git worktrees only.${NC}"
    echo -e "${RED}Running it here would overwrite your production database!${NC}"
    echo ""
    echo -e "${YELLOW}Current directory: $(pwd)${NC}"
    echo -e "${YELLOW}.git is a directory = main repository${NC}"
    echo ""
    echo -e "${GREEN}To set up a worktree:${NC}"
    echo "  1. Create task in vibe-factory UI"
    echo "  2. Click 'Start' to auto-create worktree"
    echo "  3. Setup runs automatically in worktree"
    echo ""
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    exit 1
fi

# Verify we're in a worktree (.git should be a file pointing to main repo)
if [ ! -f .git ]; then
    echo -e "${RED}❌ ERROR: Not in a git worktree!${NC}"
    echo "This script requires a git worktree environment."
    exit 1
fi

echo -e "${GREEN}✓ Confirmed: Running in git worktree${NC}"
echo ""

# Get the script directory (where this script is)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MAIN_REPO_DIR="$(dirname "$SCRIPT_DIR")"

# Get current worktree path
WORKTREE_PATH="$(pwd)"
WORKTREE_NAME="$(basename "$WORKTREE_PATH")"

echo "Main repo: $MAIN_REPO_DIR"
echo "Worktree:  $WORKTREE_PATH"
echo ""

# Step 1: Install dependencies
echo -e "${YELLOW}📦 Installing dependencies...${NC}"
pnpm install --silent || pnpm install

# Step 2: Allocate dedicated ports for this worktree
echo -e "${YELLOW}🔌 Allocating dedicated ports (4500+/4600+ range)...${NC}"
PORTS_JSON=$(node "$SCRIPT_DIR/worktree-dev-ports.js")
FRONTEND_PORT=$(echo "$PORTS_JSON" | jq -r '.frontend')
BACKEND_PORT=$(echo "$PORTS_JSON" | jq -r '.backend')

echo "  Frontend: $FRONTEND_PORT"
echo "  Backend:  $BACKEND_PORT"
echo ""

# Step 3: Copy dev_assets_template to dev_assets (isolated database)
echo -e "${YELLOW}💾 Setting up isolated database...${NC}"
if [ ! -d "dev_assets" ]; then
    # Fresh copy from template
    cp -R dev_assets_template/ dev_assets/
    echo "  ✓ Copied dev_assets_template to dev_assets"
elif [ -f "dev_assets/.worktree_initialized" ]; then
    # Already initialized in this worktree
    echo "  ✓ dev_assets already initialized for this worktree"
else
    # dev_assets exists but no marker - could be production db!
    DB_SIZE=$(wc -c < "dev_assets/db.sqlite" 2>/dev/null || echo "0")
    if [ "$DB_SIZE" -gt 4000000 ]; then
        echo -e "${RED}  ⚠️  WARNING: Large database detected ($(numfmt --to=iec $DB_SIZE))${NC}"
        echo -e "${RED}  This might be a production database!${NC}"
        echo -e "${YELLOW}  Skipping copy to prevent data loss.${NC}"
        echo ""
        echo "  If you need a fresh database:"
        echo "    rm -rf dev_assets && ./scripts/setup-worktree.sh"
    else
        echo "  ✓ dev_assets already exists (reusing)"
    fi
fi

# Mark as worktree-initialized
touch dev_assets/.worktree_initialized 2>/dev/null || true
echo ""

# Step 4: Run database migrations
echo -e "${YELLOW}🗄️  Running database migrations...${NC}"
WORKTREE_DB="$WORKTREE_PATH/dev_assets/db.sqlite"
cd crates/db && DATABASE_URL="sqlite://$WORKTREE_DB" sqlx migrate run && cd ../..
echo "  ✓ Migrations complete"
echo ""

# Step 5: Create/update .env file with ports
echo -e "${YELLOW}⚙️  Configuring environment variables...${NC}"
cat > .env <<EOF
# Vibe Factory Worktree Configuration
# Auto-generated by setup-worktree.sh

# Port Configuration (DO NOT CHANGE - auto-assigned)
FRONTEND_PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT

# Git Repository Scanning
GIT_SCAN_TIMEOUT_MS=30000
GIT_SCAN_HARD_TIMEOUT_MS=60000
GIT_SCAN_MAX_DEPTH=4

# Worktree Information
WORKTREE_PATH=$WORKTREE_PATH
MAIN_REPO_PATH=$MAIN_REPO_DIR
WORKTREE_NAME=$WORKTREE_NAME
EOF
echo "  ✓ Created .env with port configuration"
echo ""

# Step 6: Get task information from git branch name
BRANCH_NAME=$(git branch --show-current)
TASK_ID=$(echo "$BRANCH_NAME" | cut -d'-' -f1)
TASK_TITLE=$(echo "$BRANCH_NAME" | cut -d'-' -f2- | tr '-' ' ')

# Step 7: Generate personalized WORKTREE_README.md
echo -e "${YELLOW}📝 Creating worktree documentation...${NC}"
sed -e "s|{{FRONTEND_PORT}}|$FRONTEND_PORT|g" \
    -e "s|{{BACKEND_PORT}}|$BACKEND_PORT|g" \
    -e "s|{{TASK_ID}}|$TASK_ID|g" \
    -e "s|{{TASK_TITLE}}|$TASK_TITLE|g" \
    -e "s|{{BRANCH_NAME}}|$BRANCH_NAME|g" \
    -e "s|{{WORKTREE_PATH}}|$WORKTREE_PATH|g" \
    -e "s|{{MAIN_REPO_PATH}}|$MAIN_REPO_DIR|g" \
    "$MAIN_REPO_DIR/WORKTREE_README.md" > README_WORKTREE.md

echo "  ✓ Created README_WORKTREE.md"
echo ""

# Step 8: Summary
echo -e "${GREEN}✅ Worktree setup complete!${NC}"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}Your Development Environment:${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Frontend:  http://localhost:$FRONTEND_PORT"
echo "  Backend:   http://localhost:$BACKEND_PORT"
echo "  Database:  $WORKTREE_PATH/dev_assets/db.sqlite"
echo "  Branch:    $BRANCH_NAME"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Start servers: ${GREEN}pnpm run dev${NC}"
echo "  2. Read setup:    ${GREEN}cat README_WORKTREE.md${NC}"
echo "  3. View ports:    ${GREEN}cat .dev-ports.json${NC}"
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
