// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StationTransition = { id: string, workflow_id: string, source_station_id: string, target_station_id: string, condition: string | null, label: string | null, condition_type: string | null, condition_value: string | null, created_at: string, updated_at: string, };
