// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationTransition } from "./StationTransition";
import type { WorkflowStation } from "./WorkflowStation";

export type WorkflowWithDetails = { stations: Array<WorkflowStation>, transitions: Array<StationTransition>, id: string, project_id: string, name: string, description: string | null, created_at: string, updated_at: string, };
