// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowStation = { id: string, workflow_id: string, name: string, position: bigint, description: string | null, x_position: number, y_position: number, agent_id: string | null, station_prompt: string | null, output_context_keys: string | null, created_at: string, updated_at: string, };
